//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Notification
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestMessage", Namespace="http://tesco.com/appstore/messages/1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ServiceRequestOfNotifyResponse7WwHBPJi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.NotifyRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ServiceRequestOfGetListNotificationHistoryByCustomerIdResponse7WwHBPJi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.GetListNotificationHistoryByCustomerIdRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ServiceRequestOfGetNotificationHistoryByIdResponse7WwHBPJi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.GetNotificationHistoryByIdRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ServiceRequestOfResendNotificacionByNotificationHistoryIDResponse7WwHBPJi))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ResendNotificacionByNotificationHistoryIDRequest))]
    public partial class RequestMessage : object
    {
        
        private Notification.CallContext callContextField;
        
        private string messageIdField;
        
        private string requestNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.CallContext callContext
        {
            get
            {
                return this.callContextField;
            }
            set
            {
                this.callContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestName
        {
            get
            {
                return this.requestNameField;
            }
            set
            {
                this.requestNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="")]
    public partial class CallContext : object
    {
        
        private string channelField;
        
        private string businessField;
        
        private string customerSegmentField;
        
        private Notification.UserIdentity userIdentityField;
        
        private string storeIdField;
        
        private string productInstanceField;
        
        private string languageField;
        
        private string regionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string business
        {
            get
            {
                return this.businessField;
            }
            set
            {
                this.businessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string customerSegment
        {
            get
            {
                return this.customerSegmentField;
            }
            set
            {
                this.customerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Notification.UserIdentity userIdentity
        {
            get
            {
                return this.userIdentityField;
            }
            set
            {
                this.userIdentityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string storeId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string productInstance
        {
            get
            {
                return this.productInstanceField;
            }
            set
            {
                this.productInstanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestOfNotifyResponse7WwHBPJi", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.Core.MessageTypes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.NotifyRequest))]
    public partial class ServiceRequestOfNotifyResponse7WwHBPJi : Notification.RequestMessage
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyRequest", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class NotifyRequest : Notification.ServiceRequestOfNotifyResponse7WwHBPJi
    {
        
        private string NotificationTypeField;
        
        private System.Collections.Generic.Dictionary<string, string> PlaceHolderTemplateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PlaceHolderTemplate
        {
            get
            {
                return this.PlaceHolderTemplateField;
            }
            set
            {
                this.PlaceHolderTemplateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestOfGetListNotificationHistoryByCustomerIdResponse7WwHBPJi", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.Core.MessageTypes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.GetListNotificationHistoryByCustomerIdRequest))]
    public partial class ServiceRequestOfGetListNotificationHistoryByCustomerIdResponse7WwHBPJi : Notification.RequestMessage
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetListNotificationHistoryByCustomerIdRequest", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class GetListNotificationHistoryByCustomerIdRequest : Notification.ServiceRequestOfGetListNotificationHistoryByCustomerIdResponse7WwHBPJi
    {
        
        private string BusinessField;
        
        private string ChannelField;
        
        private System.Nullable<long> CustomerIDField;
        
        private System.Nullable<System.DateTime> EndUtcDateField;
        
        private System.Nullable<int> ItemsPerPageField;
        
        private string[] NotificationNameListField;
        
        private System.Nullable<int> NotificationTypeField;
        
        private System.Nullable<int> PageNumberField;
        
        private string RecipientField;
        
        private System.Nullable<System.DateTime> StartUtcDateField;
        
        private System.Nullable<short> StatusField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Business
        {
            get
            {
                return this.BusinessField;
            }
            set
            {
                this.BusinessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndUtcDate
        {
            get
            {
                return this.EndUtcDateField;
            }
            set
            {
                this.EndUtcDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ItemsPerPage
        {
            get
            {
                return this.ItemsPerPageField;
            }
            set
            {
                this.ItemsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] NotificationNameList
        {
            get
            {
                return this.NotificationNameListField;
            }
            set
            {
                this.NotificationNameListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PageNumber
        {
            get
            {
                return this.PageNumberField;
            }
            set
            {
                this.PageNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Recipient
        {
            get
            {
                return this.RecipientField;
            }
            set
            {
                this.RecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartUtcDate
        {
            get
            {
                return this.StartUtcDateField;
            }
            set
            {
                this.StartUtcDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestOfGetNotificationHistoryByIdResponse7WwHBPJi", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.Core.MessageTypes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.GetNotificationHistoryByIdRequest))]
    public partial class ServiceRequestOfGetNotificationHistoryByIdResponse7WwHBPJi : Notification.RequestMessage
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetNotificationHistoryByIdRequest", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class GetNotificationHistoryByIdRequest : Notification.ServiceRequestOfGetNotificationHistoryByIdResponse7WwHBPJi
    {
        
        private string BusinessField;
        
        private string ChannelField;
        
        private long CustomerIDField;
        
        private long NotificationHistoryIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Business
        {
            get
            {
                return this.BusinessField;
            }
            set
            {
                this.BusinessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NotificationHistoryId
        {
            get
            {
                return this.NotificationHistoryIdField;
            }
            set
            {
                this.NotificationHistoryIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceRequestOfResendNotificacionByNotificationHistoryIDResponse7WwHBPJi", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.Core.MessageTypes")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ResendNotificacionByNotificationHistoryIDRequest))]
    public partial class ServiceRequestOfResendNotificacionByNotificationHistoryIDResponse7WwHBPJi : Notification.RequestMessage
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResendNotificacionByNotificationHistoryIDRequest", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class ResendNotificacionByNotificationHistoryIDRequest : Notification.ServiceRequestOfResendNotificacionByNotificationHistoryIDResponse7WwHBPJi
    {
        
        private string BusinessField;
        
        private string ChannelField;
        
        private long CustomerIDField;
        
        private long NotificationInfoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Business
        {
            get
            {
                return this.BusinessField;
            }
            set
            {
                this.BusinessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NotificationInfoId
        {
            get
            {
                return this.NotificationInfoIdField;
            }
            set
            {
                this.NotificationInfoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentity", Namespace="")]
    public partial class UserIdentity : object
    {
        
        private string IdField;
        
        private string DisplayNameField;
        
        private string AuthenticationTypeField;
        
        private bool IsAuthenticatedField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AuthenticationType
        {
            get
            {
                return this.AuthenticationTypeField;
            }
            set
            {
                this.AuthenticationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsAuthenticated
        {
            get
            {
                return this.IsAuthenticatedField;
            }
            set
            {
                this.IsAuthenticatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseMessage", Namespace="http://tesco.com/appstore/messages/1")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ErrorResponseMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.NotifyResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.GetListNotificationHistoryByCustomerIdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.GetNotificationHistoryByIdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.ResendNotificacionByNotificationHistoryIDResponse))]
    public partial class ResponseMessage : object
    {
        
        private string errorDetailsField;
        
        private string errorMessageField;
        
        private string requestMessageIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorDetails
        {
            get
            {
                return this.errorDetailsField;
            }
            set
            {
                this.errorDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestMessageId
        {
            get
            {
                return this.requestMessageIdField;
            }
            set
            {
                this.requestMessageIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponseMessage", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.Core.MessageTypes")]
    public partial class ErrorResponseMessage : Notification.ResponseMessage
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotifyResponse", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class NotifyResponse : Notification.ResponseMessage
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetListNotificationHistoryByCustomerIdResponse", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class GetListNotificationHistoryByCustomerIdResponse : Notification.ResponseMessage
    {
        
        private Notification.NotificationHistory notificationHistoryResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.NotificationHistory notificationHistoryResponse
        {
            get
            {
                return this.notificationHistoryResponseField;
            }
            set
            {
                this.notificationHistoryResponseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetNotificationHistoryByIdResponse", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class GetNotificationHistoryByIdResponse : Notification.ResponseMessage
    {
        
        private Notification.NotificationHistoryItem notificationHistoryItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.NotificationHistoryItem notificationHistoryItem
        {
            get
            {
                return this.notificationHistoryItemField;
            }
            set
            {
                this.notificationHistoryItemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResendNotificacionByNotificationHistoryIDResponse", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class ResendNotificacionByNotificationHistoryIDResponse : Notification.ResponseMessage
    {
        
        private Notification.ResendEmailResult resendEmailResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.ResendEmailResult resendEmailResult
        {
            get
            {
                return this.resendEmailResultField;
            }
            set
            {
                this.resendEmailResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationHistory", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class NotificationHistory : object
    {
        
        private int CurrentPageField;
        
        private int ItemsPerPageField;
        
        private Notification.NotificationHistoryItem[] NotificationHistoryItemListField;
        
        private int TotalPagesField;
        
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPage
        {
            get
            {
                return this.CurrentPageField;
            }
            set
            {
                this.CurrentPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemsPerPage
        {
            get
            {
                return this.ItemsPerPageField;
            }
            set
            {
                this.ItemsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Notification.NotificationHistoryItem[] NotificationHistoryItemList
        {
            get
            {
                return this.NotificationHistoryItemListField;
            }
            set
            {
                this.NotificationHistoryItemListField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationHistoryItem", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class NotificationHistoryItem : Notification.NotificationMetadataHistory
    {
        
        private string BusinessField;
        
        private string ChannelField;
        
        private long CustomerNumberField;
        
        private string MailBodyField;
        
        private bool NotificationHasContentField;
        
        private int NotificationTemplateVersionField;
        
        private string NotificationTemplateXslContentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Business
        {
            get
            {
                return this.BusinessField;
            }
            set
            {
                this.BusinessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel
        {
            get
            {
                return this.ChannelField;
            }
            set
            {
                this.ChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerNumber
        {
            get
            {
                return this.CustomerNumberField;
            }
            set
            {
                this.CustomerNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailBody
        {
            get
            {
                return this.MailBodyField;
            }
            set
            {
                this.MailBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotificationHasContent
        {
            get
            {
                return this.NotificationHasContentField;
            }
            set
            {
                this.NotificationHasContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotificationTemplateVersion
        {
            get
            {
                return this.NotificationTemplateVersionField;
            }
            set
            {
                this.NotificationTemplateVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationTemplateXslContent
        {
            get
            {
                return this.NotificationTemplateXslContentField;
            }
            set
            {
                this.NotificationTemplateXslContentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationMetadataHistory", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Notification.NotificationHistoryItem))]
    public partial class NotificationMetadataHistory : object
    {
        
        private long NotificationIdField;
        
        private string NotificationRecipientField;
        
        private string NotificationSubjectField;
        
        private string NotificationTemplateNameField;
        
        private int NotificationTypeField;
        
        private string NotificationXmlContentField;
        
        private System.Nullable<System.DateTime> SentUTCDateField;
        
        private short StatusField;
        
        private string StatusErrorMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NotificationId
        {
            get
            {
                return this.NotificationIdField;
            }
            set
            {
                this.NotificationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationRecipient
        {
            get
            {
                return this.NotificationRecipientField;
            }
            set
            {
                this.NotificationRecipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationSubject
        {
            get
            {
                return this.NotificationSubjectField;
            }
            set
            {
                this.NotificationSubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationTemplateName
        {
            get
            {
                return this.NotificationTemplateNameField;
            }
            set
            {
                this.NotificationTemplateNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationXmlContent
        {
            get
            {
                return this.NotificationXmlContentField;
            }
            set
            {
                this.NotificationXmlContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SentUTCDate
        {
            get
            {
                return this.SentUTCDateField;
            }
            set
            {
                this.SentUTCDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusErrorMessage
        {
            get
            {
                return this.StatusErrorMessageField;
            }
            set
            {
                this.StatusErrorMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResendEmailResult", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.NotificationService")]
    public partial class ResendEmailResult : object
    {
        
        private string[] ErrorsField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Notification.INotificationService")]
    public interface INotificationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/Notify", ReplyAction="http://tempuri.org/INotificationService/NotifyResponse")]
        System.Threading.Tasks.Task NotifyAsync(string notificationType, System.Collections.Generic.Dictionary<string, string> notificationDetails, Notification.CallContext callContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/GetListNotificationHistoryByCustomerId", ReplyAction="http://tempuri.org/INotificationService/GetListNotificationHistoryByCustomerIdRes" +
            "ponse")]
        System.Threading.Tasks.Task<Notification.NotificationHistory> GetListNotificationHistoryByCustomerIdAsync(Notification.CallContext callContext, System.Nullable<long> customerID, string business, string channel, string recipient, string subject, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<short> status, System.Nullable<int> notificationType, string[] notificationNameList, System.Nullable<int> pageNumber, System.Nullable<int> itemsPerPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/GetNotificationHistoryById", ReplyAction="http://tempuri.org/INotificationService/GetNotificationHistoryByIdResponse")]
        System.Threading.Tasks.Task<Notification.NotificationHistoryItem> GetNotificationHistoryByIdAsync(Notification.CallContext callContext, long customerID, long notificationHistoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/ResendNotificacionByNotificationHistoryID" +
            "", ReplyAction="http://tempuri.org/INotificationService/ResendNotificacionByNotificationHistoryID" +
            "Response")]
        System.Threading.Tasks.Task<Notification.ResendEmailResult> ResendNotificacionByNotificationHistoryIDAsync(Notification.CallContext callContext, long customerID, long notificationInfoId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface INotificationServiceChannel : Notification.INotificationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class NotificationServiceClient : System.ServiceModel.ClientBase<Notification.INotificationService>, Notification.INotificationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotificationServiceClient() : 
                base(NotificationServiceClient.GetDefaultBinding(), NotificationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INotificationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), NotificationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotificationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task NotifyAsync(string notificationType, System.Collections.Generic.Dictionary<string, string> notificationDetails, Notification.CallContext callContext)
        {
            return base.Channel.NotifyAsync(notificationType, notificationDetails, callContext);
        }
        
        public System.Threading.Tasks.Task<Notification.NotificationHistory> GetListNotificationHistoryByCustomerIdAsync(Notification.CallContext callContext, System.Nullable<long> customerID, string business, string channel, string recipient, string subject, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate, System.Nullable<short> status, System.Nullable<int> notificationType, string[] notificationNameList, System.Nullable<int> pageNumber, System.Nullable<int> itemsPerPage)
        {
            return base.Channel.GetListNotificationHistoryByCustomerIdAsync(callContext, customerID, business, channel, recipient, subject, startDate, endDate, status, notificationType, notificationNameList, pageNumber, itemsPerPage);
        }
        
        public System.Threading.Tasks.Task<Notification.NotificationHistoryItem> GetNotificationHistoryByIdAsync(Notification.CallContext callContext, long customerID, long notificationHistoryId)
        {
            return base.Channel.GetNotificationHistoryByIdAsync(callContext, customerID, notificationHistoryId);
        }
        
        public System.Threading.Tasks.Task<Notification.ResendEmailResult> ResendNotificacionByNotificationHistoryIDAsync(Notification.CallContext callContext, long customerID, long notificationInfoId)
        {
            return base.Channel.ResendNotificacionByNotificationHistoryIDAsync(callContext, customerID, notificationInfoId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotificationService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:81/NotificationService/NotificationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotificationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INotificationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotificationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INotificationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INotificationService,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tesco.com/appstore/proxy/1", ConfigurationName="Notification.IRemoteServiceProxyContract")]
    public interface IRemoteServiceProxyContract
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tesco.com/appstore/proxy/1/IRemoteServiceProxyContract/Send", ReplyAction="http://tesco.com/appstore/proxy/1/IRemoteServiceProxyContract/SendResponse")]
        System.Threading.Tasks.Task<Notification.ResponseMessage> SendAsync(Notification.RequestMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tesco.com/appstore/proxy/1/IRemoteServiceProxyContract/SendRequestXml", ReplyAction="http://tesco.com/appstore/proxy/1/IRemoteServiceProxyContract/SendRequestXmlRespo" +
            "nse")]
        System.Threading.Tasks.Task<string> SendRequestXmlAsync(string requestXml);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tesco.com/appstore/proxy/1/IRemoteServiceProxyContract/Post")]
        System.Threading.Tasks.Task PostAsync(Notification.RequestMessage request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface IRemoteServiceProxyContractChannel : Notification.IRemoteServiceProxyContract, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class RemoteServiceProxyContractClient : System.ServiceModel.ClientBase<Notification.IRemoteServiceProxyContract>, Notification.IRemoteServiceProxyContract
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public RemoteServiceProxyContractClient() : 
                base(RemoteServiceProxyContractClient.GetDefaultBinding(), RemoteServiceProxyContractClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IRemoteServiceProxyContract.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteServiceProxyContractClient(EndpointConfiguration endpointConfiguration) : 
                base(RemoteServiceProxyContractClient.GetBindingForEndpoint(endpointConfiguration), RemoteServiceProxyContractClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteServiceProxyContractClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RemoteServiceProxyContractClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteServiceProxyContractClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RemoteServiceProxyContractClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public RemoteServiceProxyContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Notification.ResponseMessage> SendAsync(Notification.RequestMessage request)
        {
            return base.Channel.SendAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> SendRequestXmlAsync(string requestXml)
        {
            return base.Channel.SendRequestXmlAsync(requestXml);
        }
        
        public System.Threading.Tasks.Task PostAsync(Notification.RequestMessage request)
        {
            return base.Channel.PostAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteServiceProxyContract))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IRemoteServiceProxyContract))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:81/NotificationService/NotificationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return RemoteServiceProxyContractClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IRemoteServiceProxyContract);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return RemoteServiceProxyContractClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IRemoteServiceProxyContract);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IRemoteServiceProxyContract,
        }
    }
}
