//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubsPayment", Namespace="")]
    public partial class SubsPayment : object
    {
        
        private decimal AmountField;
        
        private string CardTokenField;
        
        private int CurrentPlanIdField;
        
        private long CustomerSubscriptionIdField;
        
        private bool IsSwitchedTodayField;
        
        private int NewPlanIdField;
        
        private int OldPlanIdField;
        
        private long PackageExecutionHistoryIdField;
        
        private long PaymentHistoryIdField;
        
        private long PaymentIdField;
        
        private Scheduler.CallContext contextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardToken
        {
            get
            {
                return this.CardTokenField;
            }
            set
            {
                this.CardTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentPlanId
        {
            get
            {
                return this.CurrentPlanIdField;
            }
            set
            {
                this.CurrentPlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerSubscriptionId
        {
            get
            {
                return this.CustomerSubscriptionIdField;
            }
            set
            {
                this.CustomerSubscriptionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSwitchedToday
        {
            get
            {
                return this.IsSwitchedTodayField;
            }
            set
            {
                this.IsSwitchedTodayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NewPlanId
        {
            get
            {
                return this.NewPlanIdField;
            }
            set
            {
                this.NewPlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OldPlanId
        {
            get
            {
                return this.OldPlanIdField;
            }
            set
            {
                this.OldPlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PackageExecutionHistoryId
        {
            get
            {
                return this.PackageExecutionHistoryIdField;
            }
            set
            {
                this.PackageExecutionHistoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PaymentHistoryId
        {
            get
            {
                return this.PaymentHistoryIdField;
            }
            set
            {
                this.PaymentHistoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PaymentId
        {
            get
            {
                return this.PaymentIdField;
            }
            set
            {
                this.PaymentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Scheduler.CallContext context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="")]
    public partial class CallContext : object
    {
        
        private string channelField;
        
        private string businessField;
        
        private string customerSegmentField;
        
        private Scheduler.UserIdentity userIdentityField;
        
        private string storeIdField;
        
        private string productInstanceField;
        
        private string languageField;
        
        private string regionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string business
        {
            get
            {
                return this.businessField;
            }
            set
            {
                this.businessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string customerSegment
        {
            get
            {
                return this.customerSegmentField;
            }
            set
            {
                this.customerSegmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public Scheduler.UserIdentity userIdentity
        {
            get
            {
                return this.userIdentityField;
            }
            set
            {
                this.userIdentityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string storeId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string productInstance
        {
            get
            {
                return this.productInstanceField;
            }
            set
            {
                this.productInstanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentity", Namespace="")]
    public partial class UserIdentity : object
    {
        
        private string IdField;
        
        private string DisplayNameField;
        
        private string AuthenticationTypeField;
        
        private bool IsAuthenticatedField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AuthenticationType
        {
            get
            {
                return this.AuthenticationTypeField;
            }
            set
            {
                this.AuthenticationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool IsAuthenticated
        {
            get
            {
                return this.IsAuthenticatedField;
            }
            set
            {
                this.IsAuthenticatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubsNotification", Namespace="")]
    public partial class SubsNotification : object
    {
        
        private string CardTokenField;
        
        private Scheduler.CallContext ContextField;
        
        private double CustomerDSTotalAmountField;
        
        private double CustomerDeliveryTotalAmountField;
        
        private int CustomerOrdersTotalNumberField;
        
        private double CustomerSavingsAmountField;
        
        private Scheduler.Money FinalDiscountedAmountField;
        
        private bool IsTrialPlanField;
        
        private System.DateTime NextRenewalDateField;
        
        private string NotificationTypeField;
        
        private int PlanIdField;
        
        private bool ShouldBeNotifiedField;
        
        private int SwitchplanIdField;
        
        private long TransactionIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardToken
        {
            get
            {
                return this.CardTokenField;
            }
            set
            {
                this.CardTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Scheduler.CallContext Context
        {
            get
            {
                return this.ContextField;
            }
            set
            {
                this.ContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CustomerDSTotalAmount
        {
            get
            {
                return this.CustomerDSTotalAmountField;
            }
            set
            {
                this.CustomerDSTotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CustomerDeliveryTotalAmount
        {
            get
            {
                return this.CustomerDeliveryTotalAmountField;
            }
            set
            {
                this.CustomerDeliveryTotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerOrdersTotalNumber
        {
            get
            {
                return this.CustomerOrdersTotalNumberField;
            }
            set
            {
                this.CustomerOrdersTotalNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CustomerSavingsAmount
        {
            get
            {
                return this.CustomerSavingsAmountField;
            }
            set
            {
                this.CustomerSavingsAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Scheduler.Money FinalDiscountedAmount
        {
            get
            {
                return this.FinalDiscountedAmountField;
            }
            set
            {
                this.FinalDiscountedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsTrialPlan
        {
            get
            {
                return this.IsTrialPlanField;
            }
            set
            {
                this.IsTrialPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NextRenewalDate
        {
            get
            {
                return this.NextRenewalDateField;
            }
            set
            {
                this.NextRenewalDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationType
        {
            get
            {
                return this.NotificationTypeField;
            }
            set
            {
                this.NotificationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanId
        {
            get
            {
                return this.PlanIdField;
            }
            set
            {
                this.PlanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShouldBeNotified
        {
            get
            {
                return this.ShouldBeNotifiedField;
            }
            set
            {
                this.ShouldBeNotifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SwitchplanId
        {
            get
            {
                return this.SwitchplanIdField;
            }
            set
            {
                this.SwitchplanIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Money", Namespace="http://schemas.datacontract.org/2004/07/Tesco.Com.AppStore.Core.MessageTypes")]
    public partial class Money : object
    {
        
        private System.Nullable<decimal> AmountField;
        
        private string RegionNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionName
        {
            get
            {
                return this.RegionNameField;
            }
            set
            {
                this.RegionNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceNotificationEntity", Namespace="")]
    public partial class ServiceNotificationEntity : object
    {
        
        private string CountField;
        
        private string CountTypeField;
        
        private string JobNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountType
        {
            get
            {
                return this.CountTypeField;
            }
            set
            {
                this.CountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName
        {
            get
            {
                return this.JobNameField;
            }
            set
            {
                this.JobNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="Scheduler.ISchedulerService")]
    public interface ISchedulerService
    {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ISchedulerService/RenewAllSubscriptions")]
        System.Threading.Tasks.Task RenewAllSubscriptionsAsync(Scheduler.SubsPayment[] subsPaymentList);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ISchedulerService/SendAllNotifications")]
        System.Threading.Tasks.Task SendAllNotificationsAsync(Scheduler.SubsNotification[] notificationList);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="urn:ISchedulerService/SendServiceNotifications")]
        System.Threading.Tasks.Task SendServiceNotificationsAsync(Scheduler.ServiceNotificationEntity[] serviceRecordsList);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public interface ISchedulerServiceChannel : Scheduler.ISchedulerService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.0")]
    public partial class SchedulerServiceClient : System.ServiceModel.ClientBase<Scheduler.ISchedulerService>, Scheduler.ISchedulerService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SchedulerServiceClient() : 
                base(SchedulerServiceClient.GetDefaultBinding(), SchedulerServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISchedulerService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchedulerServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SchedulerServiceClient.GetBindingForEndpoint(endpointConfiguration), SchedulerServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchedulerServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SchedulerServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchedulerServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SchedulerServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SchedulerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task RenewAllSubscriptionsAsync(Scheduler.SubsPayment[] subsPaymentList)
        {
            return base.Channel.RenewAllSubscriptionsAsync(subsPaymentList);
        }
        
        public System.Threading.Tasks.Task SendAllNotificationsAsync(Scheduler.SubsNotification[] notificationList)
        {
            return base.Channel.SendAllNotificationsAsync(notificationList);
        }
        
        public System.Threading.Tasks.Task SendServiceNotificationsAsync(Scheduler.ServiceNotificationEntity[] serviceRecordsList)
        {
            return base.Channel.SendServiceNotificationsAsync(serviceRecordsList);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISchedulerService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISchedulerService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:81/SchedulerService/SchedulerService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SchedulerServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISchedulerService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SchedulerServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISchedulerService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISchedulerService,
        }
    }
}
